name = "lbfgsb"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) Regents of the University of California"
license = "BSD-3"
description = "lbfgsb optimization library"
homepage = "https://github.com/jacobwilliams/lbfgsb"

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = true