ddot – lbfgsb
ddot Function
41 statements
Source File
public function ddot(n, dx, incx, dy, incy)
forms the dot product of two vectors. uses unrolled loops for increments equal to one.
Author
jack dongarra, linpack, 3/11/78.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in) :: dx(*)
integer, intent(in) :: incx
real(kind=wp), intent(in) :: dy(*)
integer, intent(in) :: incy
Return Value real(kind=wp)
Called by
Source Code
      real(wp) function ddot(n,dx,incx,dy,incy)
      implicit none
      integer,intent(in) :: n
      real(wp),intent(in) :: dx(*)
      integer,intent(in) :: incx
      real(wp),intent(in) :: dy(*)
      integer,intent(in) :: incy
      real(wp) :: dtemp
      integer :: i , ix , iy , m , mp1
      ddot = zero
      dtemp = zero
      if ( n<=0 ) return
      if ( incx==1 .and. incy==1 ) then
         ! code for both increments equal to 1
         ! clean-up loop
         m = mod(n,5)
         if ( m/=0 ) then
            do i = 1 , m
               dtemp = dtemp + dx(i)*dy(i)
            end do
            if ( n<5 ) then
               ddot = dtemp
               return
            end if
         end if
         mp1 = m + 1
         do i = mp1 , n , 5
            dtemp = dtemp + dx(i)*dy(i) + dx(i+1)*dy(i+1) + &
                    dx(i+2)*dy(i+2) + dx(i+3)*dy(i+3) + dx(i+4)*dy(i+4)
         end do
         ddot = dtemp
      else
         ! code for unequal increments or equal increments
         ! not equal to 1
         ix = 1
         iy = 1
         if ( incx<0 ) ix = (-n+1)*incx + 1
         if ( incy<0 ) iy = (-n+1)*incy + 1
         do i = 1 , n
            dtemp = dtemp + dx(ix)*dy(iy)
            ix = ix + incx
            iy = iy + incy
         end do
         ddot = dtemp
      end if
      end function ddot
Call graph
cauchy calls ddot, bmv
dpofa calls ddot
dtrsl calls ddot
formk calls ddot, dpofa, dtrsl
lnsrlb calls ddot
mainlb calls ddot, cauchy, formk, lnsrlb, matupd, formt, subsm, cmprlb
matupd calls ddot
bmv calls dtrsl
formt calls dpofa
setulb calls mainlb
subsm calls dtrsl
cmprlb calls bmv